CREATE TABLE SPRING_AI_CHAT_MEMORY(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    content LONGVARCHAR NOT NULL,
    type VARCHAR(50) NOT NULL,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_conversation_id ON SPRING_AI_CHAT_MEMORY(conversation_id);
CREATE INDEX idx_timestamp ON SPRING_AI_CHAT_MEMORY("timestamp");